// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zywjsozsmnjajwirkcsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5d2pzb3pzbW5qYWp3aXJrY3N1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4Njc1MDQsImV4cCI6MjA3MjQ0MzUwNH0.f-PLKLJjFV2hUfT_H35Nk_MWcbwEi7OK5DfnMBGOH6s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});